version: 0.0
os: windows
files:
  - source: \
    destination: C:\inetpub\wwwroot
hooks:
  BeforeInstall:
    - location: \scripts\before-install.bat
      timeout: 900
  AfterInstall:
    - location: \scripts\install_requirements.bat
      timeout: 6000
      runas: root
  ApplicationStart:
    - location: \scripts\collectstatic.sh
      timeout: 3000
      runas: root
  ValidateService:
    - location: \scripts\run_migrations.bat
      timeout: 3000
      runas: root
