version: 0.0
os: windows
files:
  - source: \
    destination: f:\Python\Api_new\chat
    
hooks:
  AfterInstall:
    - location: /scripts/install_requirements.sh
      timeout: 6000
      runas: root
  ApplicationStart:
    - location: /scripts/collectstatic.sh
      timeout: 3000
      runas: root
  ValidateService:
    - location: /scripts/run_migrations.sh
      timeout: 3000
      runas: root
