version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/api

hooks:
  AfterInstall:
    - location: /scripts/install_requirements.sh
      timeout: 6000
      runas: root
  ApplicationStart:
    - location: /scripts/collectstatic.sh
      timeout: 3000
      runas: root
  ValidateService:
    - location: /scripts/run_migrations.sh
      timeout: 3000
      runas: root
